import { decodeJsonPayload, GrottoConnection, type TrailersPayload } from './connection.js';
import { methodWebSocketUrl } from './method-url.js';
import { unwrapGrpcMessage, wrapGrpcMessage } from '../framing/grpc-message.js';

/** Matches the Rpc interface generated by ts-proto (`outputServices=default`). */
export interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): Promise<Uint8Array>;
  serverStreamingRequest(
    service: string,
    method: string,
    data: Uint8Array
  ): AsyncIterable<Uint8Array>;
  bidirectionalStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array>;
}

export class GrottoRpcError extends Error {
  constructor(
    readonly code: number,
    message: string
  ) {
    super(message);
    this.name = 'GrottoRpcError';
  }
}

export type GrottoRpcOptions = {
  /** Optional metadata attached to every RPC (sent in the HEADERS frame). */
  metadata?: Record<string, unknown>;
};

/**
 * ts-proto Rpc implementation over the Grotto WebSocket protocol.
 * One WebSocket is opened per RPC or stream.
 */
export class GrottoRpc implements Rpc {
  constructor(
    private readonly baseUrl: string,
    private readonly options: GrottoRpcOptions = {}
  ) {}

  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array> {
    return this.runUnary(service, method, data);
  }

  clientStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): Promise<Uint8Array> {
    return this.runClientStream(service, method, data);
  }

  serverStreamingRequest(
    service: string,
    method: string,
    data: Uint8Array
  ): AsyncIterable<Uint8Array> {
    return this.runServerStream(service, method, data);
  }

  bidirectionalStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array> {
    return this.runBidiStream(service, method, data);
  }

  private methodUrl(service: string, method: string): string {
    return methodWebSocketUrl(this.baseUrl, `/${service}/${method}`);
  }

  private async runUnary(service: string, method: string, data: Uint8Array): Promise<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    try {
      await session.start();
      await session.sendMessage(data);
      await session.finishSending();
      return await session.awaitUnaryResponse();
    } finally {
      conn.close();
    }
  }

  private async runClientStream(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): Promise<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    try {
      await session.start();
      for await (const chunk of data) {
        await session.sendMessage(chunk);
      }
      await session.finishSending();
      return await session.awaitUnaryResponse();
    } finally {
      conn.close();
    }
  }

  private runServerStream(
    service: string,
    method: string,
    data: Uint8Array
  ): AsyncIterable<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    return {
      [Symbol.asyncIterator]: () => this.iterateServerStream(session, data, conn),
    };
  }

  private async *iterateServerStream(
    session: RpcSession,
    data: Uint8Array,
    conn: GrottoConnection
  ): AsyncGenerator<Uint8Array> {
    try {
      await session.start();
      await session.sendMessage(data);
      await session.finishSending();
      while (true) {
        const next = await session.nextMessage();
        if (next.done) {
          return;
        }
        yield next.value;
      }
    } finally {
      conn.close();
    }
  }

  private runBidiStream(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    return {
      [Symbol.asyncIterator]: () => this.iterateBidiStream(session, data, conn),
    };
  }

  private async *iterateBidiStream(
    session: RpcSession,
    data: AsyncIterable<Uint8Array>,
    conn: GrottoConnection
  ): AsyncGenerator<Uint8Array> {
    await session.start();
    const writer = (async () => {
      try {
        for await (const chunk of data) {
          await session.sendMessage(chunk);
        }
        await session.finishSending();
      } catch (err) {
        session.fail(err);
        throw err;
      }
    })();

    try {
      while (true) {
        const next = await session.nextMessage();
        if (next.done) {
          return;
        }
        yield next.value;
      }
    } finally {
      conn.close();
      await writer.catch(() => undefined);
    }
  }
}

class RpcSession {
  private readonly messages: Uint8Array[] = [];
  private trailers: TrailersPayload | null = null;
  private failure: Error | null = null;
  private waiters: Array<() => void> = [];

  constructor(
    private readonly conn: GrottoConnection,
    private readonly metadata: Record<string, unknown> = {}
  ) {
    this.conn.setHandlers({
      onHeaders: () => undefined,
      onMessage: (payload) => {
        this.messages.push(decodeMessagePayload(payload));
        this.notify();
      },
      onTrailers: (payload) => {
        this.trailers = decodeJsonPayload<TrailersPayload>(payload);
        this.notify();
      },
      onCancel: () => {
        this.fail(new GrottoRpcError(1, 'call cancelled'));
      },
      onClose: () => {
        if (!this.trailers && !this.failure) {
          this.fail(new GrottoRpcError(14, 'grotto: WebSocket closed'));
        }
      },
    });
  }

  async start(): Promise<void> {
    await this.conn.connect();
    await this.conn.sendHeaders({ metadata: this.metadata });
  }

  async sendMessage(data: Uint8Array): Promise<void> {
    await this.conn.sendMessage(wrapGrpcMessage(data));
  }

  async finishSending(): Promise<void> {
    await this.conn.sendHalfClose();
  }

  fail(err: unknown): void {
    if (this.failure) {
      return;
    }
    this.failure = err instanceof Error ? err : new Error(String(err));
    this.notify();
  }

  async awaitUnaryResponse(): Promise<Uint8Array> {
    while (true) {
      if (this.failure) {
        throw this.failure;
      }
      if (this.trailers) {
        if (this.trailers.code !== 0) {
          throw new GrottoRpcError(this.trailers.code, this.trailers.details);
        }
        if (this.messages.length === 0) {
          throw new GrottoRpcError(12, 'No message received');
        }
        return this.messages[0]!;
      }
      await this.wait();
    }
  }

  async nextMessage(): Promise<IteratorResult<Uint8Array>> {
    while (true) {
      if (this.failure) {
        throw this.failure;
      }
      if (this.messages.length > 0) {
        return { value: this.messages.shift()!, done: false };
      }
      if (this.trailers) {
        if (this.trailers.code !== 0) {
          throw new GrottoRpcError(this.trailers.code, this.trailers.details);
        }
        return { value: undefined, done: true };
      }
      await this.wait();
    }
  }

  private wait(): Promise<void> {
    return new Promise((resolve) => {
      this.waiters.push(resolve);
    });
  }

  private notify(): void {
    const waiters = this.waiters;
    this.waiters = [];
    for (const resolve of waiters) {
      resolve();
    }
  }
}

function decodeMessagePayload(payload: Uint8Array): Uint8Array {
  try {
    return unwrapGrpcMessage(payload);
  } catch {
    return payload;
  }
}
