import { decodeJsonPayload, GrottoConnection, type TrailersPayload } from './connection.js';
import {
  BIDI_CLIENT_LEG_TIMEOUT_MS,
  GROTTO_BIDI_LEG_CLIENT,
  GROTTO_BIDI_LEG_HEADER,
  GROTTO_BIDI_LEG_SERVER,
  GROTTO_SESSION_ID_HEADER,
  methodRpcUrl,
} from './method-url.js';
import { unwrapGrpcMessage, wrapGrpcMessage } from '../framing/grpc-message.js';

/** Matches the Rpc interface generated by ts-proto (`outputServices=default`). */
export interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): Promise<Uint8Array>;
  serverStreamingRequest(
    service: string,
    method: string,
    data: Uint8Array
  ): AsyncIterable<Uint8Array>;
  bidirectionalStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array>;
}

export class GrottoRpcError extends Error {
  constructor(
    readonly code: number,
    message: string
  ) {
    super(message);
    this.name = 'GrottoRpcError';
  }
}

export type GrottoRpcOptions = {
  /** Optional metadata attached to every RPC (sent in the HEADERS frame). */
  metadata?: Record<string, unknown>;
};

/**
 * ts-proto Rpc implementation over Grotto HTTP streaming (GRTC frames in request/response bodies).
 * One HTTP POST per RPC or stream.
 */
export class GrottoRpc implements Rpc {
  constructor(
    private readonly baseUrl: string,
    private readonly options: GrottoRpcOptions = {}
  ) {}

  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array> {
    return this.runUnary(service, method, data);
  }

  clientStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): Promise<Uint8Array> {
    return this.runClientStream(service, method, data);
  }

  serverStreamingRequest(
    service: string,
    method: string,
    data: Uint8Array
  ): AsyncIterable<Uint8Array> {
    return this.runServerStream(service, method, data);
  }

  bidirectionalStreamingRequest(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array> {
    return this.runBidiStream(service, method, data);
  }

  private methodUrl(service: string, method: string): string {
    return methodRpcUrl(this.baseUrl, `/${service}/${method}`);
  }

  private async runUnary(service: string, method: string, data: Uint8Array): Promise<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    try {
      await session.start();
      await session.sendMessage(data);
      await session.finishSending();
      return await session.awaitUnaryResponse();
    } finally {
      conn.close();
    }
  }

  private async runClientStream(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): Promise<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    try {
      await session.start();
      for await (const chunk of data) {
        await session.sendMessage(chunk);
      }
      await session.finishSending();
      return await session.awaitUnaryResponse();
    } finally {
      conn.close();
    }
  }

  private runServerStream(
    service: string,
    method: string,
    data: Uint8Array
  ): AsyncIterable<Uint8Array> {
    const conn = new GrottoConnection(this.methodUrl(service, method));
    const session = new RpcSession(conn, this.options.metadata);
    return {
      [Symbol.asyncIterator]: () => this.iterateServerStream(session, data, conn),
    };
  }

  private async *iterateServerStream(
    session: RpcSession,
    data: Uint8Array,
    conn: GrottoConnection
  ): AsyncGenerator<Uint8Array> {
    try {
      await session.start();
      await session.sendMessage(data);
      await session.finishSending();
      while (true) {
        const next = await session.nextMessage();
        if (next.done) {
          return;
        }
        yield next.value;
      }
    } finally {
      conn.close();
    }
  }

  private runBidiStream(
    service: string,
    method: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncIterable<Uint8Array> {
    const url = this.methodUrl(service, method);
    const serverConn = new GrottoConnection(url, {
      requestHeaders: { [GROTTO_BIDI_LEG_HEADER]: GROTTO_BIDI_LEG_SERVER },
    });
    const serverSession = new RpcSession(serverConn, this.options.metadata);
    return {
      [Symbol.asyncIterator]: () =>
        this.iterateBidiStream(serverSession, serverConn, url, data),
    };
  }

  private async *iterateBidiStream(
    serverSession: RpcSession,
    serverConn: GrottoConnection,
    url: string,
    data: AsyncIterable<Uint8Array>
  ): AsyncGenerator<Uint8Array> {
    const toClose: GrottoConnection[] = [serverConn];
    let clientLegTimer: ReturnType<typeof setTimeout> | null = null;

    try {
      await serverSession.start();
      await serverSession.finishSending();
      await serverConn.awaitResponseHeaders();

      const sessionId = serverConn.getResponseHeader(GROTTO_SESSION_ID_HEADER);
      if (!sessionId) {
        throw new Error('grotto: bidi server leg did not return Grotto-Session-Id');
      }

      let clientLegConnected = false;

      const clientLegPromise = (async () => {
        const clientConn = new GrottoConnection(url, {
          requestHeaders: {
            [GROTTO_SESSION_ID_HEADER]: sessionId,
            [GROTTO_BIDI_LEG_HEADER]: GROTTO_BIDI_LEG_CLIENT,
          },
        });
        toClose.push(clientConn);
        const clientSession = new RpcSession(clientConn, this.options.metadata);
        await clientSession.start();
        clientLegConnected = true;
        if (clientLegTimer) {
          clearTimeout(clientLegTimer);
          clientLegTimer = null;
        }
        for await (const chunk of data) {
          await clientSession.sendMessage(chunk);
        }
        await clientSession.finishSending();
        await clientSession.drainResponse();
      })().catch((err) => {
        serverSession.fail(err);
        throw err;
      });

      clientLegTimer = setTimeout(() => {
        if (!clientLegConnected) {
          serverSession.fail(
            new Error('grotto: client leg not opened within 10s of server leg')
          );
          serverConn.close();
        }
      }, BIDI_CLIENT_LEG_TIMEOUT_MS);

      while (true) {
        const next = await serverSession.nextMessage();
        if (next.done) {
          break;
        }
        yield next.value;
      }

      await clientLegPromise;
    } finally {
      if (clientLegTimer) {
        clearTimeout(clientLegTimer);
      }
      for (const conn of toClose) {
        conn.close();
      }
    }
  }
}

class RpcSession {
  private readonly messages: Uint8Array[] = [];
  private trailers: TrailersPayload | null = null;
  private failure: Error | null = null;
  private waiters: Array<() => void> = [];

  constructor(
    private readonly conn: GrottoConnection,
    private readonly metadata: Record<string, unknown> = {}
  ) {
    this.conn.setHandlers({
      onHeaders: () => undefined,
      onMessage: (payload) => {
        this.messages.push(decodeMessagePayload(payload));
        this.notify();
      },
      onTrailers: (payload) => {
        this.trailers = decodeJsonPayload<TrailersPayload>(payload);
        this.notify();
      },
      onCancel: () => {
        this.fail(new GrottoRpcError(1, 'call cancelled'));
      },
      onError: (err) => {
        this.fail(err);
      },
      onClose: () => {
        if (!this.trailers && !this.failure) {
          this.fail(new GrottoRpcError(14, 'grotto: response stream closed'));
        }
      },
    });
  }

  async start(): Promise<void> {
    await this.conn.connect();
    await this.conn.sendHeaders({ metadata: this.metadata });
  }

  async sendMessage(data: Uint8Array): Promise<void> {
    await this.conn.sendMessage(wrapGrpcMessage(data));
  }

  async finishSending(): Promise<void> {
    await this.conn.sendHalfClose();
  }

  fail(err: unknown): void {
    if (this.failure) {
      return;
    }
    this.failure = err instanceof Error ? err : new Error(String(err));
    this.notify();
  }

  async awaitUnaryResponse(): Promise<Uint8Array> {
    while (true) {
      if (this.failure) {
        throw this.failure;
      }
      if (this.trailers) {
        if (this.trailers.code !== 0) {
          throw new GrottoRpcError(this.trailers.code, this.trailers.details);
        }
        if (this.messages.length === 0) {
          throw new GrottoRpcError(12, 'No message received');
        }
        return this.messages[0]!;
      }
      await this.wait();
    }
  }

  /** Consumes the HTTP response through TRAILERS (for legs with no response messages). */
  async drainResponse(): Promise<void> {
    while (true) {
      if (this.failure) {
        throw this.failure;
      }
      if (this.trailers) {
        if (this.trailers.code !== 0) {
          throw new GrottoRpcError(this.trailers.code, this.trailers.details);
        }
        return;
      }
      await this.wait();
    }
  }

  async nextMessage(): Promise<IteratorResult<Uint8Array>> {
    while (true) {
      if (this.failure) {
        throw this.failure;
      }
      if (this.messages.length > 0) {
        return { value: this.messages.shift()!, done: false };
      }
      if (this.trailers) {
        if (this.trailers.code !== 0) {
          throw new GrottoRpcError(this.trailers.code, this.trailers.details);
        }
        return { value: undefined, done: true };
      }
      await this.wait();
    }
  }

  private wait(): Promise<void> {
    return new Promise((resolve) => {
      this.waiters.push(resolve);
    });
  }

  private notify(): void {
    const waiters = this.waiters;
    this.waiters = [];
    for (const resolve of waiters) {
      resolve();
    }
  }
}

function decodeMessagePayload(payload: Uint8Array): Uint8Array {
  try {
    return unwrapGrpcMessage(payload);
  } catch {
    return payload;
  }
}
